### ISSUE TITLE
Missing a tutorial how to install, confgure and run DashZero on SHPI.zero

### ISSUE THREAD

**Issue by maichai** [panbachi/dashzero#1]
Hi panbachi,
I am already a fan of DashZero without running it yet :)
Would you mind giving us here a short tutorial on how to install, configure and run DashZero on the SHPI.zero?

I would really love to have that on my SHPI.zero!!

**Comment by lukastillmann** [comment]
Me, too. I am still waiting for my SHPI, but this would be the best use case for the device

**Comment by napsio** [comment]
Hi,

I've added an installation instruction in the readme.

Best regards
